version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: spendy_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - spendy_db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spendy_api
    command: flask run --host=0.0.0.0 --port=5000 --reload
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spendy_processor
    environment:
      - LOGLEVEL=WARNING
    command: watchmedo auto-restart --ignore-patterns='.git/*' --patterns='*.py' --recursive -- python react-app/public/run.py
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
      - api

  frontend:
    image: node:18-alpine
    working_dir: /app
    container_name: spendy_frontend
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./react-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
      - processor

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: spendy_phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

volumes:
  spendy_db_data:
