version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  flask:
    build:
      context: ./react-app  # Adjust path if necessary
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./react-app:/app  # Mount your Flask app directory
    depends_on:
      - redis
